-- Seed data: NIUM training & capacity building calendar (generated from production).
-- Applied automatically by `supabase db reset` / `supabase start`.

INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('38f03105-0d9c-408f-a621-894148dfed60','Municipal Asset Management and Land Value Capture','2026-08-19','2026-08-21','','Asset Monetization, Land Value Capture, GIS Asset Mapping','Commissioners, Revenue Officers, Town Planners','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('c01d18b2-f868-4fe6-bd53-82b6efefa2fa','Smart Infrastructure Management','2026-08-20','2026-08-21','','','Municipal Commissioners, Engineers,Town Planners','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('40d11e44-ec38-4935-82cf-9907eaf17cc2','Project Life Cycles & Appraisal Methods','2026-08-28','2026-08-29','Project Management','Project Life Cycle, Project Appraisal','','Dr KS','MA&UD','MCR-HRD',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('8e4bb604-dd79-4618-af9c-f5e75c6669ae','Urban Ecology & Sustainable Development Planning','2026-09-16','2026-09-18','Energy, Environment & Climate Resilience','Lifestyle for Environment (Mission LiFE)','','Dr KS','MA&UD','MCR-HRD',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('e6e3eeb6-ff53-4a0e-838a-3b703780e111','Transforming Urban Governance: Institutions, Innovation and Inclusion','2026-09-18','2026-09-19','Urban & Rural Development','Urban Governance & Institutional Systems','','Dr KS','MA&UD','MCR-HRD',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('9c47815e-0242-4738-a3d4-296c4dbbd4ec','Satellite Mapping and Spatial Planning for Urban Infrastructure Management','2026-09-21','2026-09-23','Digital Governance, Data & Emerging Technologies','Emerging Technologies (GIS, Drones, IoT, Blockchain etc.)','','Dr KS','MA&UD','MCR-HRD',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('1ac7dbff-b72f-4138-8597-703511a1d991','Project Life Cycles & Appraisal Methods','2026-09-29','2026-09-30','Project Management','Project Life Cycle, Project Appraisal','','Dr KS','MA&UD','MCR-HRD',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('16bfa5d5-5b47-4800-8ce3-98397caf045e','Gender Inclusive Urban Planning and Gender Responsive Budgeting for ULBs','2026-10-08','2026-10-09','','Safe Cities, Women''s Mobility, Public Space Design, Inclusive Planning, Gender Audits Gender Budgeting, Outcome Monitoring, Gender Indicators, Resource Allocation','Town Planners, Municipal Commissioners','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('bb47c148-4f14-4fed-952b-5486c85268b1','Digital Transformation in Government','2026-10-09','2026-10-10','','','Town Planners, Municipal Commissioners','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('fb3521a7-fd1b-4b11-ba26-9fa20a81206b','Inclusive Cities Planning for Vulnerable Groups','2026-10-09','2026-10-10','','Child-Friendly Cities, Elderly-Friendly Cities, Universal Accessibility, Slum Upgrading','Town Planners, Welfare Officers, Municipal Staff','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('06f5d162-8999-48ff-a8f5-3a5d1ccb2803','Climate Resilient Cities and Urban Adaptation Planning','2026-10-15','2026-10-16','','Climate Risk Assessment, Heat Action Plans, Urban Resilience, Nature-Based Solutions','','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('953886ab-5aaf-4917-b91a-2a9da843eca4','Urban Climate Finance and Green Investments & Urban Flood Management and Disaster Resilience','2026-10-29','2026-10-30','','Green Bonds, Climate Funds, Carbon Finance, Climate Budgeting','Municipal Commissioners, Finance Officers, Accounts Officers, City Engineers, Project Directors,','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('3b363408-0bc1-4f24-a19e-7909ac175ad7','Climate Smart Urban Infrastructure','2026-10-30','2026-10-31','','Flood Mapping, Stormwater Management, Early Warning Systems','Municipal Engineers, Executive Engineers, Deputy Engineers, Town Planning Officers','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('f2ce6229-a763-46d5-af75-bfa36ddefe19','Circular Economy and Solid Waste Management','2026-11-05','2026-11-06','','Resilient Infrastructure, Green Buildings, Sustainable Urban Systems','Sanitary Inspectors, Municipal Health Officers, Environmental Engineers, SWM Managers, Commissioners, Public Health Officials','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('7eb43dea-3008-4b45-90dc-c14de8f46e06','Water Sensitive Urban Planning','2026-11-12','2026-11-13','','Urban Lakes, Groundwater Recharge, Wetlands, Stormwater Reuse','Municipal Engineers, Town Planning Officers, Environmental Engineers, Water Supply Engineers,  Urban Planners','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('d490090a-7e82-44cd-bd98-a4211152b4cd','Urban Lake Rejuvenation and Restoration','2026-11-19','2026-11-20','','Lake Restoration, STPs, Catchment Management, Biodiversity Conservation','Municipal Commissioners, Engineers, Environmental Engineers, Lake Protection Committee Members, Town Planning Officers','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('ae921863-aef7-4b9d-bd87-c1197ef0b632','Integrated Urban Resilience Programme','2026-11-26','2026-11-27','','Governance, Climate Resilience, Municipal Finance','Municipal Commissioners, Additional Commissioners, City Managers, Municipal Engineers, Finance Officers','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('06f237be-cbe2-4133-9bec-1657cf23b984','Smart Cities, AI and Urban Innovation','2026-12-03','2026-12-04','','AI Applications, Digital Twins, Urban Analytics, Smart Governance','Municipal Commissioners, IT Officers,,  Town Planning Officers, Data Analysts','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('3f7d181f-16f8-4739-be9f-a82d856f3e86','Transit-Oriented Development and Sustainable Mobility','2026-12-10','2026-12-11','','TOD, Public Transport, NMT, Mobility Planning','Town Planning Officers, City Planners, Municipal Engineers','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('0ed19715-8979-434f-8667-5cfa86fcd568','Urban Data Analytics and GIS for Municipal Governance','2026-12-17','2026-12-18','','GIS Applications, Urban Dashboards, Data-Driven Governance','GIS Specialists, Town Planning Officers, IT Officers, Municipal Engineers,  Revenue Officers','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO public.events (id,title,start_date,end_date,theme,subtheme,participants,coordinator,department,source,description,location) VALUES ('5b2fb3bb-87b9-4d82-aa81-bae5737b1c19','Digital Transformation in Government','2026-12-17','2026-12-18','','','Municipal Commissioners, Additional Commissioners, Administrative Officers, IT Officers','NIUM','MA&UD','NIUM',NULL,NULL) ON CONFLICT (id) DO NOTHING;
