/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerticalsUrbanInformaticsRouteImport } from './routes/verticals.urban-informatics'
import { Route as VerticalsTrainingCapacityRouteImport } from './routes/verticals.training-capacity'
import { Route as VerticalsResearchDevelopmentRouteImport } from './routes/verticals.research-development'
import { Route as VerticalsProjectManagementRouteImport } from './routes/verticals.project-management'
import { Route as ProjectsCompletedRouteImport } from './routes/projects.completed'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalsUrbanInformaticsRoute =
  VerticalsUrbanInformaticsRouteImport.update({
    id: '/verticals/urban-informatics',
    path: '/verticals/urban-informatics',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalsTrainingCapacityRoute =
  VerticalsTrainingCapacityRouteImport.update({
    id: '/verticals/training-capacity',
    path: '/verticals/training-capacity',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalsResearchDevelopmentRoute =
  VerticalsResearchDevelopmentRouteImport.update({
    id: '/verticals/research-development',
    path: '/verticals/research-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalsProjectManagementRoute =
  VerticalsProjectManagementRouteImport.update({
    id: '/verticals/project-management',
    path: '/verticals/project-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsCompletedRoute = ProjectsCompletedRouteImport.update({
  id: '/projects/completed',
  path: '/projects/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/team': typeof TeamRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/verticals/project-management': typeof VerticalsProjectManagementRoute
  '/verticals/research-development': typeof VerticalsResearchDevelopmentRoute
  '/verticals/training-capacity': typeof VerticalsTrainingCapacityRoute
  '/verticals/urban-informatics': typeof VerticalsUrbanInformaticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/team': typeof TeamRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/verticals/project-management': typeof VerticalsProjectManagementRoute
  '/verticals/research-development': typeof VerticalsResearchDevelopmentRoute
  '/verticals/training-capacity': typeof VerticalsTrainingCapacityRoute
  '/verticals/urban-informatics': typeof VerticalsUrbanInformaticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/team': typeof TeamRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/verticals/project-management': typeof VerticalsProjectManagementRoute
  '/verticals/research-development': typeof VerticalsResearchDevelopmentRoute
  '/verticals/training-capacity': typeof VerticalsTrainingCapacityRoute
  '/verticals/urban-informatics': typeof VerticalsUrbanInformaticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/team'
    | '/admin'
    | '/projects/completed'
    | '/verticals/project-management'
    | '/verticals/research-development'
    | '/verticals/training-capacity'
    | '/verticals/urban-informatics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/team'
    | '/admin'
    | '/projects/completed'
    | '/verticals/project-management'
    | '/verticals/research-development'
    | '/verticals/training-capacity'
    | '/verticals/urban-informatics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calendar'
    | '/team'
    | '/_authenticated/admin'
    | '/projects/completed'
    | '/verticals/project-management'
    | '/verticals/research-development'
    | '/verticals/training-capacity'
    | '/verticals/urban-informatics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  TeamRoute: typeof TeamRoute
  ProjectsCompletedRoute: typeof ProjectsCompletedRoute
  VerticalsProjectManagementRoute: typeof VerticalsProjectManagementRoute
  VerticalsResearchDevelopmentRoute: typeof VerticalsResearchDevelopmentRoute
  VerticalsTrainingCapacityRoute: typeof VerticalsTrainingCapacityRoute
  VerticalsUrbanInformaticsRoute: typeof VerticalsUrbanInformaticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/urban-informatics': {
      id: '/verticals/urban-informatics'
      path: '/verticals/urban-informatics'
      fullPath: '/verticals/urban-informatics'
      preLoaderRoute: typeof VerticalsUrbanInformaticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/training-capacity': {
      id: '/verticals/training-capacity'
      path: '/verticals/training-capacity'
      fullPath: '/verticals/training-capacity'
      preLoaderRoute: typeof VerticalsTrainingCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/research-development': {
      id: '/verticals/research-development'
      path: '/verticals/research-development'
      fullPath: '/verticals/research-development'
      preLoaderRoute: typeof VerticalsResearchDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/project-management': {
      id: '/verticals/project-management'
      path: '/verticals/project-management'
      fullPath: '/verticals/project-management'
      preLoaderRoute: typeof VerticalsProjectManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/completed': {
      id: '/projects/completed'
      path: '/projects/completed'
      fullPath: '/projects/completed'
      preLoaderRoute: typeof ProjectsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  TeamRoute: TeamRoute,
  ProjectsCompletedRoute: ProjectsCompletedRoute,
  VerticalsProjectManagementRoute: VerticalsProjectManagementRoute,
  VerticalsResearchDevelopmentRoute: VerticalsResearchDevelopmentRoute,
  VerticalsTrainingCapacityRoute: VerticalsTrainingCapacityRoute,
  VerticalsUrbanInformaticsRoute: VerticalsUrbanInformaticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
