/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerticalsUrbanInformaticsRouteImport } from './routes/verticals.urban-informatics'
import { Route as VerticalsTrainingCapacityRouteImport } from './routes/verticals.training-capacity'
import { Route as VerticalsResearchDevelopmentRouteImport } from './routes/verticals.research-development'
import { Route as VerticalsProjectManagementRouteImport } from './routes/verticals.project-management'
import { Route as VerticalsHeritageConservationRouteImport } from './routes/verticals.heritage-conservation'
import { Route as VerticalsCommunicationOutreachRouteImport } from './routes/verticals.communication-outreach'
import { Route as ProjectsCompletedRouteImport } from './routes/projects.completed'
import { Route as CareersJobsRouteImport } from './routes/careers.jobs'
import { Route as CareersInternshipsRouteImport } from './routes/careers.internships'
import { Route as AboutMoreRouteImport } from './routes/about.more'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerticalsUrbanInformaticsRoute =
  VerticalsUrbanInformaticsRouteImport.update({
    id: '/verticals/urban-informatics',
    path: '/verticals/urban-informatics',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalsTrainingCapacityRoute =
  VerticalsTrainingCapacityRouteImport.update({
    id: '/verticals/training-capacity',
    path: '/verticals/training-capacity',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalsResearchDevelopmentRoute =
  VerticalsResearchDevelopmentRouteImport.update({
    id: '/verticals/research-development',
    path: '/verticals/research-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalsProjectManagementRoute =
  VerticalsProjectManagementRouteImport.update({
    id: '/verticals/project-management',
    path: '/verticals/project-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalsHeritageConservationRoute =
  VerticalsHeritageConservationRouteImport.update({
    id: '/verticals/heritage-conservation',
    path: '/verticals/heritage-conservation',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerticalsCommunicationOutreachRoute =
  VerticalsCommunicationOutreachRouteImport.update({
    id: '/verticals/communication-outreach',
    path: '/verticals/communication-outreach',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsCompletedRoute = ProjectsCompletedRouteImport.update({
  id: '/projects/completed',
  path: '/projects/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersJobsRoute = CareersJobsRouteImport.update({
  id: '/careers/jobs',
  path: '/careers/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersInternshipsRoute = CareersInternshipsRouteImport.update({
  id: '/careers/internships',
  path: '/careers/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMoreRoute = AboutMoreRouteImport.update({
  id: '/about/more',
  path: '/about/more',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/competitions': typeof CompetitionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/tenders': typeof TendersRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/about/more': typeof AboutMoreRoute
  '/careers/internships': typeof CareersInternshipsRoute
  '/careers/jobs': typeof CareersJobsRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/verticals/communication-outreach': typeof VerticalsCommunicationOutreachRoute
  '/verticals/heritage-conservation': typeof VerticalsHeritageConservationRoute
  '/verticals/project-management': typeof VerticalsProjectManagementRoute
  '/verticals/research-development': typeof VerticalsResearchDevelopmentRoute
  '/verticals/training-capacity': typeof VerticalsTrainingCapacityRoute
  '/verticals/urban-informatics': typeof VerticalsUrbanInformaticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/competitions': typeof CompetitionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/tenders': typeof TendersRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/about/more': typeof AboutMoreRoute
  '/careers/internships': typeof CareersInternshipsRoute
  '/careers/jobs': typeof CareersJobsRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/verticals/communication-outreach': typeof VerticalsCommunicationOutreachRoute
  '/verticals/heritage-conservation': typeof VerticalsHeritageConservationRoute
  '/verticals/project-management': typeof VerticalsProjectManagementRoute
  '/verticals/research-development': typeof VerticalsResearchDevelopmentRoute
  '/verticals/training-capacity': typeof VerticalsTrainingCapacityRoute
  '/verticals/urban-informatics': typeof VerticalsUrbanInformaticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/competitions': typeof CompetitionsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/team': typeof TeamRoute
  '/tenders': typeof TendersRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/about/more': typeof AboutMoreRoute
  '/careers/internships': typeof CareersInternshipsRoute
  '/careers/jobs': typeof CareersJobsRoute
  '/projects/completed': typeof ProjectsCompletedRoute
  '/verticals/communication-outreach': typeof VerticalsCommunicationOutreachRoute
  '/verticals/heritage-conservation': typeof VerticalsHeritageConservationRoute
  '/verticals/project-management': typeof VerticalsProjectManagementRoute
  '/verticals/research-development': typeof VerticalsResearchDevelopmentRoute
  '/verticals/training-capacity': typeof VerticalsTrainingCapacityRoute
  '/verticals/urban-informatics': typeof VerticalsUrbanInformaticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/competitions'
    | '/reset-password'
    | '/team'
    | '/tenders'
    | '/admin'
    | '/about/more'
    | '/careers/internships'
    | '/careers/jobs'
    | '/projects/completed'
    | '/verticals/communication-outreach'
    | '/verticals/heritage-conservation'
    | '/verticals/project-management'
    | '/verticals/research-development'
    | '/verticals/training-capacity'
    | '/verticals/urban-informatics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/competitions'
    | '/reset-password'
    | '/team'
    | '/tenders'
    | '/admin'
    | '/about/more'
    | '/careers/internships'
    | '/careers/jobs'
    | '/projects/completed'
    | '/verticals/communication-outreach'
    | '/verticals/heritage-conservation'
    | '/verticals/project-management'
    | '/verticals/research-development'
    | '/verticals/training-capacity'
    | '/verticals/urban-informatics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calendar'
    | '/competitions'
    | '/reset-password'
    | '/team'
    | '/tenders'
    | '/_authenticated/admin'
    | '/about/more'
    | '/careers/internships'
    | '/careers/jobs'
    | '/projects/completed'
    | '/verticals/communication-outreach'
    | '/verticals/heritage-conservation'
    | '/verticals/project-management'
    | '/verticals/research-development'
    | '/verticals/training-capacity'
    | '/verticals/urban-informatics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  CompetitionsRoute: typeof CompetitionsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeamRoute: typeof TeamRoute
  TendersRoute: typeof TendersRoute
  AboutMoreRoute: typeof AboutMoreRoute
  CareersInternshipsRoute: typeof CareersInternshipsRoute
  CareersJobsRoute: typeof CareersJobsRoute
  ProjectsCompletedRoute: typeof ProjectsCompletedRoute
  VerticalsCommunicationOutreachRoute: typeof VerticalsCommunicationOutreachRoute
  VerticalsHeritageConservationRoute: typeof VerticalsHeritageConservationRoute
  VerticalsProjectManagementRoute: typeof VerticalsProjectManagementRoute
  VerticalsResearchDevelopmentRoute: typeof VerticalsResearchDevelopmentRoute
  VerticalsTrainingCapacityRoute: typeof VerticalsTrainingCapacityRoute
  VerticalsUrbanInformaticsRoute: typeof VerticalsUrbanInformaticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/urban-informatics': {
      id: '/verticals/urban-informatics'
      path: '/verticals/urban-informatics'
      fullPath: '/verticals/urban-informatics'
      preLoaderRoute: typeof VerticalsUrbanInformaticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/training-capacity': {
      id: '/verticals/training-capacity'
      path: '/verticals/training-capacity'
      fullPath: '/verticals/training-capacity'
      preLoaderRoute: typeof VerticalsTrainingCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/research-development': {
      id: '/verticals/research-development'
      path: '/verticals/research-development'
      fullPath: '/verticals/research-development'
      preLoaderRoute: typeof VerticalsResearchDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/project-management': {
      id: '/verticals/project-management'
      path: '/verticals/project-management'
      fullPath: '/verticals/project-management'
      preLoaderRoute: typeof VerticalsProjectManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/heritage-conservation': {
      id: '/verticals/heritage-conservation'
      path: '/verticals/heritage-conservation'
      fullPath: '/verticals/heritage-conservation'
      preLoaderRoute: typeof VerticalsHeritageConservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verticals/communication-outreach': {
      id: '/verticals/communication-outreach'
      path: '/verticals/communication-outreach'
      fullPath: '/verticals/communication-outreach'
      preLoaderRoute: typeof VerticalsCommunicationOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/completed': {
      id: '/projects/completed'
      path: '/projects/completed'
      fullPath: '/projects/completed'
      preLoaderRoute: typeof ProjectsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/jobs': {
      id: '/careers/jobs'
      path: '/careers/jobs'
      fullPath: '/careers/jobs'
      preLoaderRoute: typeof CareersJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/internships': {
      id: '/careers/internships'
      path: '/careers/internships'
      fullPath: '/careers/internships'
      preLoaderRoute: typeof CareersInternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/more': {
      id: '/about/more'
      path: '/about/more'
      fullPath: '/about/more'
      preLoaderRoute: typeof AboutMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  CompetitionsRoute: CompetitionsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeamRoute: TeamRoute,
  TendersRoute: TendersRoute,
  AboutMoreRoute: AboutMoreRoute,
  CareersInternshipsRoute: CareersInternshipsRoute,
  CareersJobsRoute: CareersJobsRoute,
  ProjectsCompletedRoute: ProjectsCompletedRoute,
  VerticalsCommunicationOutreachRoute: VerticalsCommunicationOutreachRoute,
  VerticalsHeritageConservationRoute: VerticalsHeritageConservationRoute,
  VerticalsProjectManagementRoute: VerticalsProjectManagementRoute,
  VerticalsResearchDevelopmentRoute: VerticalsResearchDevelopmentRoute,
  VerticalsTrainingCapacityRoute: VerticalsTrainingCapacityRoute,
  VerticalsUrbanInformaticsRoute: VerticalsUrbanInformaticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
